{
 "title": "Flask App Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Success Rate — Trend Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "(1 - $A / ($B + ($B == 0))) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Success Rate — Snapshot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(1 - $A / ($B + ($B == 0))) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "request_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Error Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "error_count_total", "legendFormat": "__auto" }
   ]
  }
 ]
}